import { deckHistory, deckPrior } from '../lib/deckFeed';

import { NET_POSITION } from './cioMonthly.data';
import { deckGdp } from '../lib/cioGdp';
import { WORLD_MARKS, WORLD_NAMED, WORLD_SHAPES, WORLD_VIEWBOX } from './worldMap.data';

import {
  BINS,
  CIO_LATEST,
  deckVintage,
  MACRO,
  OPS,
  PERIODS,
  STATUS,
  type CioDeckData,
} from './cioMonthly';

/** The slide deck at public/deck/index.html is a self-contained file (it must open from a
 *  desktop or a USB stick), so it cannot import the fixture. Its data block is generated from
 *  the latest vintage instead, between these two marker lines, by `npm run sync:deck`; the unit
 *  test in cioMonthly.test.ts fails when the block on disk differs from what this returns. */

export const DECK_BLOCK_BEGIN =
  '  /* ==== SHARED DATA — generated from src/fixtures/cioMonthly.ts (latest vintage) by `npm run sync:deck`; edit the fixtures, not this block ==== */';
export const DECK_BLOCK_END = '  /* ==== END SHARED DATA ==== */';

export const DECK_DATA: CioDeckData = {
  GDP: deckGdp(CIO_LATEST.reportDate),
  HISTORY: deckHistory(CIO_LATEST),
  NETPOS: NET_POSITION,
  PRIOR: deckPrior(CIO_LATEST),
  PERIODS,
  ENT: CIO_LATEST.ENT,
  BINS,
  MKT: CIO_LATEST.MKT ?? [],
  MACRO,
  OPS,
  STATUS,
  VINTAGE: deckVintage(CIO_LATEST),
};

export const DECK_FIELDS = [
  'PERIODS',
  'ENT',
  'BINS',
  'MKT',
  'MACRO',
  'OPS',
  'STATUS',
  'VINTAGE',
  'PRIOR',
  'NETPOS',
  'GDP',
  'HISTORY',
] as const;

/** The lines between the markers (no trailing newline). Declared with `let` so the deck, when
 *  presented inside the dashboard, can take the report on screen instead (lib/deckFeed.ts). */
export function deckDataBlock(): string {
  return DECK_FIELDS.map((name) => `  let ${name} = ${JSON.stringify(DECK_DATA[name])};`).join(
    '\n',
  );
}

/** The country outlines for the geographic exposure map. They do not change with the report, so
 *  they are a block of their own, declared `const`: the dashboard replaces the shared data above
 *  when it feeds the deck another vintage, and there is no reason for 44 KB of coastline to travel
 *  with it. Generated by the same `npm run sync:deck`, and held to the fixture by the same drift
 *  test in cioMonthly.test.ts. */
export const DECK_WORLD_BEGIN =
  '  /* ==== WORLD OUTLINES — generated from src/fixtures/worldMap.data.ts (itself generated by tools/make_world_paths.py) by `npm run sync:deck` ==== */';
export const DECK_WORLD_END = '  /* ==== END WORLD OUTLINES ==== */';

export function deckWorldBlock(): string {
  return [
    `  const WORLD_VIEWBOX = ${JSON.stringify(WORLD_VIEWBOX)};`,
    `  const WORLD_NAMED = ${JSON.stringify(WORLD_NAMED)};`,
    `  const WORLD_MARKS = ${JSON.stringify(WORLD_MARKS)};`,
    `  const WORLD_SHAPES = ${JSON.stringify(WORLD_SHAPES)};`,
  ].join('\n');
}
