/** GENERATED by tools/fetch_macro_snapshot.py with the snapshot beside it. The shell header
 *  reads these dates without loading the full snapshot, which only the Economic Context
 *  view needs. */
export const MACRO_META = {
  retrieved: '2026-09-16',
  /** factors use monthly averages through the last complete month before retrieval */
  monthlyThrough: '2026-08',
  seriesCount: 38,
} as const;
